deployment:
  name: "simple-web"
  replicas: 1
  image: "acrinterview.azurecr.io/simple-web"
  tag: "latest"
  containerPort: 80
  requestsMemory: "7Mi"
  requestsCPU: "1m"
  limitsMemory: "14Mi"
  limitsCPU: "4m"

service:
  name: "simple-web-service"
  type: "ClusterIP"
  port: 80
  targetPort: 80

ingress:
  name: "simple-web-ingress"
  path: "/michael"
  pathType: "Prefix"
  className: "nginx"
  port: 80

autoscaler:
  name: "simple-web-autoscaler"
  minReplicaCount: 0
  maxReplicaCount: 10
  fallback:
    failureThreshold: 1
    replicas: 1
  cpu:
    metricType: "AverageValue"
    value: "2m"
  memory:
    metricType: "AverageValue"
    value: "10Mi"
  cron:
    timezone: "Israel"
    start: 0 8 * * *
    end: 0 12 * * *
    desiredReplicas: "2"
