deployment:
  name: "simple-web"
  replicas: 1
  image: "acrinterview.azurecr.io/simple-web"
  tag: "latest"
  containerPort: 80
  requestsMemory: "7Mi"
  requestsCPU: "1m"
  limitsMemory: "14Mi"
  limitsCPU: "2m"

service:
  name: "simple-web-service"
  type: "ClusterIP"
  port: 80
  targetPort: 80

ingress:
  name: "simple-web-ingress"
  path: "/michael"
  pathType: "Prefix"
  className: "nginx"
  port: 80


