apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.autoscaler.name }}
spec:
  scaleTargetRef:
    name: {{ .Values.deployment.name }}
  minReplicaCount: {{ .Values.autoscaler.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaler.maxReplicaCount }}
  triggers:
  - type: cpu
    metricType: {{ .Values.autoscaler.cpu.metricType }}
    metadata:
      value: "{{ .Values.autoscaler.cpu.value }}"
  - type: memory
    metricType: {{ .Values.autoscaler.memory.metricType }}
    metadata:
      value: "{{ .Values.autoscaler.memory.value }}"
  - type: cron
    metadata:
      timezone: {{ .Values.autoscaler.cron.timezone }}
      start: {{ .Values.autoscaler.cron.start }}
      end: {{ .Values.autoscaler.cron.end }}
      desiredReplicas: "{{ .Values.autoscaler.cron.desiredReplicas }}"
