apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.autoscaler.name }}
spec:
  scaleTargetRef:
    name: {{ .Values.deployment.name }}
  minReplicaCount: {{ .Values.autoscaler.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaler.maxReplicaCount }}
  fallback:
    failureThreshold: {{ .Values.autoscaler.fallback.failureThreshold }}
    replicas: {{ .Values.autoscaler.fallback.replicas }}
  triggers:
  - type: cpu
    metricType: {{ .Values.autoscaler.cpu.metricType }}
    metadata:
      value: "{{ .Values.autoscaler.cpu.value }}"
  - type: memory
    metricType: {{ .Values.autoscaler.memory.metricType }}
    metadata:
      value: "{{ .Values.autoscaler.memory.value }}"
  - type: cron
    metadata:
      name: {{ .Values.autoscaler.cron.peakHours.name }}
      timezone: {{ .Values.autoscaler.cron.peakHours.timezone }}
      start: {{ .Values.autoscaler.cron.peakHours.start }}
      end: {{ .Values.autoscaler.cron.peakHours.end }}
      desiredReplicas: "{{ .Values.autoscaler.cron.peakHours.desiredReplicas }}"
  - type: cron
    metadata:
      name: {{ .Values.autoscaler.cron.offPeak.name }}
      timezone: {{ .Values.autoscaler.cron.offPeak.timezone }}
      start: {{ .Values.autoscaler.cron.offPeak.start }}
      end: {{ .Values.autoscaler.cron.offPeak.end }}
      desiredReplicas: "{{ .Values.autoscaler.cron.offPeak.desiredReplicas }}"

